name: caching-proxy

services:
  web:
    build: .
    container_name: php-app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db-cache
    networks:
      - caching_proxy_net

  db-cache:
    image: redis:8.2.1
    container_name: redis-cache
    ports:
      - 6379:6379
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - caching_proxy_net

networks:
  caching_proxy_net: